name: build actions
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-16.04
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g @zeit/ncc
      - name: Debug workspace
        run: env
      - name: Install build-node-artifact
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/build-node-artifact
      - name: Install git-commit
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/git-commit
      - name: Install git-tag
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/git-tag
      - name: Install git-tag-n-commit-mvn-deploy
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/git-tag-n-commit-mvn-deploy
      - name: Install release-mvn-pkg
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/release-mvn-pkg
      - name: Install release-prepare-mvn-pkg
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/release-prepare-mvn-pkg
      - name: Install release-verify-auto-deploy
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/release-verify-auto-deploy
      - name: Install setup-maven
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/setup-maven
      - name: Install verify-mvn-dependencies
        uses: jactor-rises/actions/build-node-artifact@master
        with:
          artifact_folder: actions/verify-mvn-dependencies
      - run: date +"%Y-%m-%d:%T" > .build-date
      - name: Commit ncc build in actions
        uses: jactor-rises/actions/git-commit@master
        with:
          commit_message: "{}: Fresh build of actions with npm and ncc"
          commit_message_file: .build-date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
